routes/web.php
<?php

use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');
Route::group([], function (Router $router) {
    $router->get('/', [\App\Http\Controllers\BlogController::class, 'index'])->name('home.index');
    $router->get('/category/{category_slug?}', [\App\Http\Controllers\BlogController::class, 'category'])->name('home.category');

    $router->get('/tag/{tag}', [\App\Http\Controllers\BlogController::class, 'tag'])->name('home.tag');
    $router->get('/detail/{id}', [\App\Http\Controllers\BlogController::class, 'detail'])->name('home.detail');
    $router->get('/oauth/{driver}', [\App\Http\Controllers\AuthController::class, 'redirectToProvider'])->name('oauth');
    $router->get('/oauth/{driver}/callback', [\App\Http\Controllers\AuthController::class, 'handleProviderCallback'])->name('oauth.callback');
    $router->get('/to-login', [\App\Http\Controllers\BlogController::class, 'tologin'])->name('home.tologin');
//    $router->get('logout',[App\Http\Controllers\AuthController::class,'logout'])->name('oauth.logout');

    $router->get('/test', [\App\Http\Controllers\BlogController::class, 'test']);
});
//Route::get('home',function (){
//    return view('welcome');
//});
//Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');

app/Models/User.php
<?php

namespace App\Models;

use App\Jobs\SendResetPasswordEmailJob;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * @return string
     */
    public function getImageAttribute(): string
    {
        if ($this->profile_photo_path) {
            if (url()->isValidUrl($this->profile_photo_path)) {
                return $this->profile_photo_path;
            } else {
                return Storage::url($this->profile_photo_path);
            }
        } else {
            return 'https://ui-avatars.com/api/?name='.$this->name.'color=7F9CF5&background=EBF4FF';
        }
    }

    public function sendPasswordResetNotification($token): void
    {
        SendResetPasswordEmailJob::dispatch($this, $token)->onQueue(config('queue.queue_name.high'));
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\BlogRepository;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BlogController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        return view('blog.index');
    }

    /**
     * @param int $id
     * @param BlogRepository $repository
     * @return View
     */
    public function detail(int $id, BlogRepository $repository): View
    {
        $post = $repository->getPostById($id);
        $prev = $post->where(function (Builder $builder) use ($id, $post) {
            $builder->where('category_id', $post->category_id);
            $builder->where('id', '>', $id);
        })->orderBy('id', 'asc')->first(['id', 'title']);
        $next = $post->where(function (Builder $builder) use ($id, $post) {
            $builder->where('category_id', $post->category_id);
            $builder->where('id', '<', $id);
        })->orderBy('id', 'desc')->first(['id', 'title']);

        return view('blog.detail', compact('post', 'prev', 'next'));
    }

    /**
     * @param null|string $category_slug
     * @return View
     */
    public function category(?string $category_slug = null): View
    {
        return view('blog.category', compact('category_slug'));
    }

    /**
     * @param string $tag
     * @return View
     */
    public function tag(string $tag): View
    {
        return view('blog.tag', compact('tag'));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function toLogin(Request $request): RedirectResponse
    {
        session()->put('url.intended', $request->server('HTTP_REFERER'));

        return redirect(route('login'));
    }

    /**
     * @return View
     */
    public function test(): View
    {
        return view('blog.test');
    }
}

resources/views/blog/category.blade.php
@extends('blog.layout')

@section('content')
    <main>
        <div class="block md:flex break-all">
        <livewire:post-list-category/>
        <livewire:right-card/>
        </div>
    </main>
@endsection

resources/views/blog/comment.blade.php
@foreach($comments as $key => $comment)
    @php
        $key_add_comment = \Illuminate\Support\Str::random(10);
        $show_reply = 'show_reply' . $time;
    @endphp
    <div x-data="{ {{ $show_reply }}:false}" id="comment-{{ $comment->id }}">
        <div class="mt-2 flex flex-wrap justify-center divide-y divide-gray-200">
            <div class="w-2/12 sm:w-1/12  py-3 flex justify-start">
                <img class="h-10 w-10 rounded-full"
                     src="{{ $comment->user->image ?? '' }}">

            </div>
            <div class="w-10/12 sm:w-11/12 py-3">
                <p class="prose rounded font-light text-base text-gray flex">
                    <span>{{ $comment->user->name ?? '' }}</span> <span class="mx-2"></span><span class="mr-2">{{ $comment->created_at->diffForHumans() }}
                        </span>
                    @if(Auth::check())
                        <span class="ml-1 bg-gray-100 px-3 transition ease-in-out duration-150 hover:bg-indigo-500 hover:text-white leading-6 rounded-md text-gray-500 whitespace-no-wrap inline-flex text-sm items-center"
                              @click="{{ $show_reply }} = !{{ $show_reply }}">
                        回复
                    </span>
                    @endif
                </p>
                <div class="prose rounded divide-y max-w-none divide-gray-200 mt-3 text-base text-gray-500">
                    {!! $comment->content_str !!}
                </div>

            </div>
        </div>

        <div class="ml-10">
            <div style="display: none" x-show="{{ $show_reply }}">
                <livewire:add-comment :postId="$postId"
                                      :comment="$comment"
                                      :time="$time"
                                      :key="$key_add_comment"/>
            </div>
            @include('blog.comment',['comments' => $comment->replys,'time' => $time + 1])
        </div>


    </div>
@endforeach

resources/views/blog/detail.blade.php
@extends('blog.layout',['title'=> $post->title,'desc' => $post->introduce])
@section('css')
    <link rel="stylesheet" href="{{ asset('plugs/highlight/styles/monokai-sublime.css') }}">
@endsection
@section('js')
    <script src="{{ asset('plugs/highlight/highlight.pack.js')  }}"></script>
    <script>
        hljs.initHighlightingOnLoad();
    </script>
@endsection
@section('content')
    <div class="block md:flex break-all">
        <div class="md:w-3/4">
            <main>
                <article class="xl:divide-y xl:divide-gray-200 shadow-lg bg-white">
                    <header class="pt-5 xl:pb-2">
                        <div class="space-y-1 text-center">
                            <dl class="space-y-10">
                                <div>
                                    <dt class="sr-only">发布日期</dt>
                                    <dd class="text-base leading-6 font-medium text-gray-500">
                                        <time datetime="2020-08-25T13:00:00.000Z">{{ $post->created_at }}</time>
                                    </dd>
                                </div>
                            </dl>
                            <div>
                                <h1 class="text-2xl leading-9 font-extrabold text-gray-900 tracking-tight px-2 sm:leading-10 md:leading-14">{{ $post->title }}</h1>
                            </div>
                            <div class="mt-1">
                                <livewire:tag-list :tags="$post->tag"/>
                            </div>
                        </div>
                    </header>
                    <div class="divide-y xl:divide-y-0 divide-gray-200"
                         style="grid-template-rows:auto 1fr">
                        <div class="divide-y divide-gray-200 xl:pb-0">
                            <div class="prose max-w-none py-3 px-5">
                                {!! $post->content_str !!}
                            </div>
                        </div>
                    </div>
                    <div class="py-5 px-5">
                        @if($prev)
                            <a href="{{ route('home.detail',['id' => $prev->id]) }}"
                               class="my-5 ml-1 flex items-start space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150">
                                <div class="space-y-1">
                                    <p class="font-normal text-base text-indigo-700 hover:underline hover:text-indigo-900">
                                        上一篇：{{ $prev->title }}
                                    </p>
                                </div>
                            </a>
                        @endif
                        @if($next)
                            <a href="{{ route('home.detail',['id' => $next->id]) }}"
                               class="my-5 ml-1 flex items-start space-x-4 rounded-lg hover:bg-gray-50 transition ease-in-out duration-150">
                                <div class="space-y-1">
                                    <p class="font-normal text-base text-indigo-700 hover:underline hover:text-indigo-900">
                                        下一篇：{{ $next->title }}
                                    </p>
                                </div>
                            </a>
                        @endif
                    </div>

                </article>
                @if(Auth::check())
                    <livewire:add-comment :postId="$post->id" key="'add'.$post->id"/>
                @else
                    <div class="xl:divide-y xl:divide-gray-200 shadow-lg mt-5 py-5 bg-white flex flex-wrap justify-center px-3 lg:px-5">
                        <a class="text-indigo-600 hover:text-indigo-900" href="{{route('home.tologin')}}">登陆后方可评论！</a>
                    </div>
                @endif
                <livewire:show-comment :post="$post" :key="'show'.$post->id"/>
            </main>

        </div>
        <livewire:right-card/>
    </div>
@endsection

@section('js')
    <script src="{{ asset('js/showdown.js') }}"></script>
    <script type="text/javascript">
        function convert() {
            var text = document.getElementById("comment-composing-box").value;
            var converter = new showdown.Converter();
            var html = converter.makeHtml(text);
            document.getElementById("preview-box").style = html ? "display:block" : "display:none";
            document.getElementById("preview-box").innerHTML = html;
        }
    </script>
@endsection

resources/views/blog/index.blade.php
@extends('blog.layout')

@section('content')
    <livewire:hot-post/>
    <livewire:ad/>
    <livewire:partner-list/>
@endsection

resources/views/blog/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $title ?? blog_default_title() }}</title>
    <meta property="og:title" content="{{ $title ?? blog_default_title()}}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request()->url() }}">
    <meta property="og:image" content="{{ asset('images/logo.png') }}">
    <meta property="og:image:width" content="500">
    <meta property="og:image:height" content="500">
    <meta property="og:description" content="{{ $desc ?? blog_default_desc() }}">
    <meta property="og:site_name" content="游兴祥的个人博客">
    <meta name="keywords" content="{{ $title ?? blog_default_title() }}"/>
    <meta name="description" content="{{ $desc ?? blog_default_desc() }}"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,800,800i,900,900i&v1.7.4">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @yield('css')
    <script src="{{ asset('js/app.js')  }}" defer></script>
    @livewireStyles

</head>
<body class="bg-gray-100 antialiased leading-none" x-data="{ mobile_menu: false,show_login : false}">

<livewire:nav/>
<div class="mt-0 md:mt-5 pt-24 md:pt-0" id="components">
    <div class="max-w-screen-xl mx-auto px-4 sm:px-4 lg:px-8 py-5 bg-gray">
        @yield('content')
    </div>
</div>
@if(empty($hidden_footer))
    <livewire:footer/>
@endif
@livewireScripts
</body>
<script>
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?911cd34390e03fb45567e521bff89398";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
@yield('js')
</html>

resources/views/blog/tag.blade.php
@extends('blog.layout')

@section('content')
    <div class="block md:flex break-all">
        <livewire:post-list-tag/>
        <livewire:right-card/>
    </div>
@endsection

resources/views/blog/test.blade.php
@extends('blog.layout')
@section('css')
    <style>

        blockquote {
            border-left:#eee solid 5px;
            padding-left:20px;
        }

         ul li {
             line-height: 20px;
         }


         code {
             color:#D34B62;
             background: #F6F6F6;
         }
        }
    </style>
@endsection
@section('js')
    <script src="{{ asset('js/showdown.js') }}"></script>
    <script type="text/javascript">
        function convert(){
            var text = document.getElementById("oriContent").value;
            var converter = new showdown.Converter();
            var html = converter.makeHtml(text);
            document.getElementById("result").innerHTML = html;
        }
    </script>
@endsection
@section('content')
    {{--<div x-data="{ open: false }">--}}
    {{--<button @click="open = true">展開下拉選單</button>--}}

    {{--<ul--}}
    {{--x-show="open"--}}
    {{--@click.away="open = false"--}}
    {{-->--}}
    {{--下拉選單內容--}}
    {{--</ul>--}}
    {{--</div>--}}

    {{--<div x-data="{ tab: 'foo' }">--}}
    {{--<button :class="{ 'active': tab === 'foo' }" @click="tab = 'foo'">Foo</button>--}}
    {{--<button :class="{ 'active': tab === 'bar' }" @click="tab = 'bar'">Bar</button>--}}

    {{--<div x-show="tab === 'foo'">索引標籤 Foo</div>--}}
    {{--<div x-show="tab === 'bar'">索引標籤 Bar</div>--}}
    {{--</div>--}}

    {{--<h1>SimpleMDE Dome</h1>--}}

    {{--<div class="container">--}}
    {{--<textarea name="" rows="" cols="" id="editor"></textarea>--}}
    {{--</div>--}}


    {{--<div x-data @test-event.window="console.log($event.detail)"></div>--}}

    {{--<button x-data @click="$dispatch('test-event', 'Hello World!')">1212</button>--}}

    {{--<div x-data="{ fruit: 'apple' }">--}}
    {{--<button--}}
    {{--x-on:click="--}}
    {{--fruit = 'pear';--}}
    {{--$nextTick(() => { console.log($event.target.innerText) });--}}
    {{--"--}}
    {{--x-text="fruit"--}}
    {{--></button>--}}
    {{--</div>--}}


    {{--<div x-data="{show_login:false}" @test-event.window="console.log($event.detail.show_login)" x-show="show_login">ssss</div>--}}

    {{--<button x-data @click="$dispatch('test-event', { show_login: true })">22222</button>--}}

    {{--<div x-ref="foo"></div><button x-on:click="$refs.foo.innerText = 'bar'">你好啊</button></button>--}}
    {{--<div x-data="{open:true,login:false}">--}}
    {{--<div>--}}
    {{--<div x-show="open">--}}
    {{--你好啊--}}
    {{--</div>--}}
    {{--<button @click="login = true">--}}
    {{--登陆--}}
    {{--</button>--}}

    {{--</div>--}}
    {{--<button @click="open = false">--}}
    {{--点击--}}
    {{--</button>--}}

    {{--</div>--}}
    {{--<div x-show="login">--}}
    {{--登陆--}}
    {{--</div>--}}
@endsection